name: Build and Push Docker Image
description: A composite action to build and push a Docker image with caching

inputs:
  docker-tag:
    description: "Docker tag (e.g., v1.0 or latest)"
    required: true
  github-token:
    description: "GitHub token for authentication"
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3.6.0
      with:
        platforms: all

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3.10.0
      with:
        install: true

    - name: Convert Repository Owner to Lowercase
      id: lowercase_repo_owner
      run: echo "lowercase_owner=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT
      shell: bash

    - name: Extract Docker metadata
      id: metadata
      uses: docker/metadata-action@v5.7.0
      with:
        images: |
          ghcr.io/${{ github.repository_owner }}/fastapi-app
        tags: |
          type=raw,value=${{ inputs.docker-tag }}
          type=raw,value=latest

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3.4.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.github-token }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v6.16.0
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        cache-from: type=registry,ref=ghcr.io/${{ steps.lowercase_repo_owner.outputs.lowercase_owner }}/fastapi-app:cache
        cache-to: type=registry,ref=ghcr.io/${{ steps.lowercase_repo_owner.outputs.lowercase_owner }}/fastapi-app:cache,mode=max
        tags: ${{ steps.metadata.outputs.tags }}